### ISSUE TITLE
DEV BRANCH: New password hashing algorithm breaks compatibility with PHP 5.3/5.4

### ISSUE THREAD

**Issue by SierraKomodo** [SierraKomodo/komodo-control-panel#2]
NOTE: Issue will be left open during development phase to allow further discussion on this matter. Currently, I have opted to run a PHP version check and use sha256 for versions older than 5.6.

Introduced with https://github.com/SierraKomodo/komodo-control-panel/commit/4fb7dcf79da0d756188fa2f913bbf9568f824850

Relevant code is in https://github.com/SierraKomodo/komodo-control-panel/blob/4fb7dcf79da0d756188fa2f913bbf9568f824850/page/register.php, lines 71-76. Going to have to add a PHP version check which reverts to sha256 or another 5.3 supported hashing algorithm for PHP versions older than 5.6.

**Comment by johnhoulder** [comment]
https://github.com/ircmaxell/password_compat seems to resolve the issue from what I remember

**Comment by SierraKomodo** [comment]
Looks like it has some issues with certain versions of php 5.3 (Namely those older than 5.3.7) based on the readme and the currently open issues. Using this would require me to note exactly which versions of 5.3 can still be supported and under what circumstances (Apparently some distributions have backported fixes to 5.3.3, while others haven't, which would make that a headache and a half to sort out).

For the time being, based on what I've been told by others (And the apparent NSA standard of using sha256), I'm going to follow my original plan with bcrypt for 5.6+ and sha256 for anything older than that.
